version: '3'

networks:
    laravel-application:

services:
    nginx:
        image: nginx:latest
        container_name: nginx_container
        ports:
            - "8080:80"
        volumes:
            - "./src:/var/www/html"
            - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
        networks:
            - laravel-application

    php:
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: php_image
        container_name: php_container
        ports:
            - "9000:9000"
        volumes:
            - "./src:/var/www/html"
        networks:
            - laravel-application

    mysql:
        image: mysql:latest
        container_name: mysql_container
        ports:
            - "3306:3306"
        volumes:
            - "./mysql:/var/lib/mysql"
        restart: unless-stopped
        tty: true
        environment:
            MYSQL_DATABASE: laravel-application
            MYSQL_ROOT_PASSWORD: root
            MYSQL_SERVICE_TAG: dev
            MYSQL_SERVICE_NAME: mysql
        networks:
            - laravel-application

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_container
        depends_on:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8081:80"
        networks:
            - laravel-application